services:
  goxii:
    build: .
    container_name: goxii-proxy
    ports:
      - 8081:8081
    command: sh ./bin/docker/build.sh
    environment:
      - DESTINATION=
      - PORT=
    volumes:
      - ./resources/:/usr/src/app/resources
    networks:
      - test-net
      - proxy-net
  
networks:
  proxy-net:
    external: true
  test-net:
    external: true
